apiVersion: apps/v1
kind: Deployment
metadata:
  name: calmapp
  labels:
    app: calmapp
spec:
  selector:
    matchLabels:
      app: calmapp
  template:
    metadata:
      labels:
        app: calmapp
    spec:
      containers:
        - image: test000.azurecr.io/calm-app:1.0
          name: calmapp
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: calmapp-service
  labels:
    app: calmapp
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
  selector:
    app: calmapp
  type: LoadBalancer
